# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

FROM amazonlinux@sha256:8ff52854cd5e22cd24fcb18ce14680d43910c4816eaedb4d94d6e5586773407b
RUN yum install wget make gcc gcc-c++ openssl-devel bzip2-devel libffi-devel zlib-devel libicu60 file lsof which procps tar git -y
RUN <<-EOF
    pushd /tmp
    wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
    tar -xvf Python-3.9.6.tgz
    cd Python-3.9.6
    ./configure --enable-optimizations --enable-shared
    make altinstall
    echo "/usr/local/lib" >> /etc/ld.so.conf.d/python3.9.conf
    ldconfig
    ln -s /usr/local/bin/python3.9 /usr/bin/python3
    popd
EOF
RUN curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64" && mv "bazelisk-linux-amd64" /usr/local/bin/bazel && chmod a+x /usr/local/bin/bazel
